org.gradle.jvmargs=-Xmx16G
org.gradle.daemon=false
org.gradle.warning.mode=all
ort.gradle.paralell=true
systemProp.net.minecraftforge.gradle.check.certs=false


mod_id=effortless
mod_name=Effortless Structure: Survival Edition
mod_license=LGPLv3
mod_version=3.4.0-survival.1
mod_group_id=dev.huskuraft.effortless
mod_authors=Huskcasaca and GarfieldZero
mod_description=Unofficial survival-focused fork of Effortless Structure.
mod_display_url=https://github.com/GarfieldZero/effortless
mod_sources_url=https://github.com/GarfieldZero/effortless
mod_issues_url=https://github.com/GarfieldZero/effortless/issues

mod_modrinth_id=
mod_curseforge_id=
